# Generated by Django 6.0 on 2025-12-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(help_text='e.g. Red, Blue, Black', max_length=100),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(help_text='e.g. S, M, L, XL, 32, 34', max_length=100),
        ),
    ]
