# Generated by Django 6.0 on 2025-12-24 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('reason', models.CharField(choices=[('DEFECT', 'Defective Product'), ('WRONG_SIZE', 'Wrong Size'), ('WRONG_COLOR', 'Wrong Color'), ('NOT_AS_EXPECTED', 'Not as Expected'), ('CUSTOMER_CHANGE', 'Customer Changed Mind'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_gst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='sales.sale')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('refund_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('return_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.return')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.saleitem')),
            ],
        ),
    ]
